source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", "~> 7.0"
gem "webrick"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Use bcrypt for Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"

# Use JWT for API authentication
gem "jwt"
gem "rack-cors"

# Use sqlite3 for local, postgres for production
gem "sqlite3", "~> 1.4", groups: [:development, :test]
gem "pg", group: :production

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "faker"
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
  gem "shoulda-matchers", "~> 5.0"
end